# Generated by Django 5.2.4 on 2025-08-23 10:10

import apps.admin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True, unique=True)),
                ("email", models.TextField(blank=True)),
                ("phones", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("query", models.CharField(max_length=255)),
                ("result", models.JSONField(default=dict)),
                (
                    "companies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="search_queries",
                        to="admin_app.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="query",
            field=models.ManyToManyField(
                related_name="company_queries", to="admin_app.searchquery"
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("language", models.CharField(default="pl", max_length=8)),
                ("country", models.CharField(default="PL", max_length=8)),
                (
                    "credentials",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.admin_app.models.save_file
                    ),
                ),
                (
                    "token",
                    models.FileField(
                        blank=True, null=True, upload_to=apps.admin_app.models.save_file
                    ),
                ),
                (
                    "results",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_queries",
                        to="admin_app.searchquery",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ManyToManyField(
                related_name="search_queries", to="admin_app.user"
            ),
        ),
    ]
