# Generated by Django 5.2.4 on 2025-08-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="searchquery",
            options={},
        ),
        migrations.RenameField(
            model_name="company",
            old_name="emails",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="result",
        ),
        migrations.AddField(
            model_name="searchquery",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_queries",
                to="admin_app.company",
            ),
        ),
    ]
