# Generated by Django 5.2.4 on 2025-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_searchquery_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.RemoveField(
            model_name="searchquery",
            name="company",
        ),
        migrations.AddField(
            model_name="searchquery",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="search_queries", to="admin_app.company"
            ),
        ),
    ]
