# Generated by Django 5.2.4 on 2025-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0004_remove_company_industry_remove_company_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="user",
            field=models.ManyToManyField(
                related_name="search_queries", to="admin_app.user"
            ),
        ),
    ]
