# Generated by Django 5.2.4 on 2025-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_searchquery_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="query",
            field=models.ManyToManyField(
                related_name="company_queries", to="admin_app.searchquery"
            ),
        ),
    ]
