# Generated by Django 5.2.4 on 2025-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_company_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="PL", max_length=8),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(default="pl", max_length=8),
        ),
    ]
