# Generated by Django 5.2.4 on 2025-08-12 16:37

import apps.admin_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0007_user_country_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credentials",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.admin_app.models.save_file
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.admin_app.models.save_file
            ),
        ),
    ]
