# Generated by Django 5.2.4 on 2025-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_user_credentials_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="phones",
            field=models.TextField(blank=True),
        ),
    ]
