# Generated by Django 5.2.4 on 2025-08-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_alter_company_address_alter_company_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
