# Generated by Django 5.2.4 on 2025-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0010_alter_company_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
