[project]
name = "email-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "dotenv>=0.9.9",
    "geocoder>=1.38.1",
    "google-search-results>=2.4.2",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
    "thefuck>=3.32",
]
